INSTRUCTION_BOX_STROKE_COLOR = "#333333"
HEADER_SEP_COLOR = "#666666"

FONT_FAMILY_TEXT = 'Georgia'
FONT_FAMILY_TECH = 'Arial Black'

DASH = '3,2'

DIMENSIONS_FONT_COLOR = 'black'
DIMENSIONS_LINE_COLOR = 'black'
ACTIVE_STROKE_COLOR = 'red'
DEPTH_HOLE_COLOR = 'gray'
